version: "3"
services:
  compose-db:
    image: db-service_image
    build: .
    ports:
      - "8082:8082"
    networks:
      - answers-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - answers-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  answers-mysql: